cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:id>/', views.customer_detail, name= 'customer_detail'),
]

johnsonshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls', namespace='customer')),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    address = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.email}, {self.address}'

    class Meta:
        db_table = 'customer'

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Customer.objects.create(user=instance)
    
    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.customer.save()

customer/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse

# Create your views here.

@login_required
def customer_list(request):
    try:
        user = request.user
        if user.is_authenticated and user.is_staff:  # Update the condition here
            users = User.objects.all()
            return render(request, 'customer/list.html', {'users' : users})
        else:
            return redirect('account:login')
    except Exception as e:
        return HttpResponse("Error: {}".format(str(e)), status=500)

@login_required
def customer_detail(request, id):
    try:
        user = get_object_or_404(User, id=id)
        return render(request, 'customer/detail.html', {'user' : user})
    except Exception as e:
        return HttpResponse("Error: {}".format(str(e)), status=500)

customer/templates/customer/detail.html
{% extends 'base.html' %}

{% block title %}Customer Details{% endblock %}

{% block content %}

    <div class="container mt-5">
        <h1>Customer Details</h1>
        <div class="mt-3">
            <h4>Customer: {{ user.first_name }} {{ user.last_name }}</h4>
            <p>
                Address: {{ user.customer.address }}<br>
                Email: {{ user.email }}
            </p>
            <div class="text-right">
                <a href="{% url 'customer:customer_list' %}" class="btn btn-primary">Back</a>
            </div>
        </div>
    </div>
    
{% endblock %}

customer/templates/customer/list.html
{% extends 'base.html' %}

{% block title %}Customer List{% endblock %}

{% block content %}

    <div class="container mt-5">
        <h1>Customer List</h1>
        {% for user in users %}
        <div class="mt-3">
            <h4><a href="{% url 'customer:customer_detail' id=user.pk %}">{{ user.first_name }} {{ user.last_name }}</a></h4>
            <p>
                Their username is {{ user.username }} and they live at {{ user.customer.address }}.
                You can reach them at {{ user.email }}
            </p>
        </div>
        {% endfor %}
    </div>
    
{% endblock %}