account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'account'

urlpatterns = [
    path('login/', 
        auth_views.LoginView.as_view(
        template_name='registration/login.html'), name='login'),
    path('logout/', 
        auth_views.LogoutView.as_view(
        template_name='registration/log_out.html'), name='logout'),
    path('', views.dashboard, name='dashboard'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

johnsonshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls', namespace='customer')),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order_list/', views.order_list, name='order_list'),
    path('order/<int:id>/', views.order_detail, name= 'order_detail'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('search/', views.product_search, name='product_search'),
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models
from store.models import Product

# Create your models here.

class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='carts')
    quantity = models.IntegerField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.product},{self.quantity},{self.created_date}'

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
    choices=PRODUCT_QUANTITY_CHOICES,
    coerce=int)
    update = forms.BooleanField(required=False,
    initial=False,
    widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from store.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, product_id):
    try:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddProductForm(request.POST)
        
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(
                product=product, 
                quantity=cd['quantity'], 
                update_quantity=cd['update'])
        return redirect('cart:cart_detail')
    except Exception as e:
        return HttpResponse("Error: {}".format(str(e)), status=500)

@require_POST
def cart_remove(request, product_id):
    try:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('cart:cart_detail')
    except Exception as e:
        return HttpResponse("Error: {}".format(str(e)), status=500)

def cart_detail(request):
    try:
        cart = Cart(request)
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                initial={'quantity': item['quantity'], 
                        'update': True})
        return render(request, 'cart/detail.html', {'cart': cart})
    except Exception as e:
        return HttpResponse("Error: {}".format(str(e)), status=500)

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Your shopping cart{% endblock %}

{% block content %}

<div class="container">
    <h1 class="mb-4">Your shopping cart</h1>
    <div class="table-responsive">
        <table class="table cart">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unit price</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}
                        {% else %}{% static 'img/no_image.png' %}{% endif %}" class="img-fluid" width="100" height="100">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post" class="d-flex">
                             {{ item.update_quantity_form.quantity }}
                             {{ item.update_quantity_form.update }}
                             <input type="submit" value="Update" class="btn btn-sm btn-primary mx-2">
                             {% csrf_token %}
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                        <input type="submit" value="Remove" class="btn btn-sm btn-danger">
                        {% csrf_token %}
                        </form>
                    </td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
                {% endwith %}
                {% endfor %}
                <tr class="total">
                    <td>Total</td>
                    <td colspan="4"></td>
                    <td class="num">${{ cart.get_total_price }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="text-right">
        {% if request.user.is_authenticated %}
          <a href="{% url 'store:product_list' %}" class="btn btn-light">Continue shopping</a>
          <a href="{% url 'orders:order_create' %}" class="btn btn-primary">
              Checkout
          </a>
        {% else %}
          <a href="{% url 'account:login' %}" class="btn btn-primary">Login</a>
        {% endif %}
      </div>
</div>

{% endblock %}