cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

johnsonshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls', namespace='customer')),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order_list/', views.order_list, name='order_list'),
    path('order/<int:id>/', views.order_detail, name= 'order_detail'),
]

orders/models.py
from django.db import models
from store.models import Product
from customer.models import Customer

# Create your models here.

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

    def save(self, *args, **kwargs):
        if not self.order.customer:
            # Set a default customer value
            self.order.customer = Customer.objects.first()
            self.order.save()
        super().save(*args, **kwargs)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address',
        'postal_code', 'city']

orders/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart

# Create your views here.

def order_create(request):
    try:
        cart = Cart(request)
        if request.method == 'POST':
            form = OrderCreateForm(request.POST)
            if form.is_valid():
                order = form.save()
                for item in cart:
                    OrderItem.objects.create(
                        order=order,
                        product=item['product'],
                        price=item['price'],
                        quantity=item['quantity'])
                # clear the cart
                cart.clear()
            return render(request,
                    'orders/order/created.html',
                    {'order': order})
        else:
            form = OrderCreateForm()
        return render(request,
            'orders/order/create.html',
            {'cart': cart, 'form': form})
    except Exception as e:
        return HttpResponse("Error: {}".format(str(e)), status=500)
    
def order_list(request):
    try:
        orders = Order.objects.all()
        return render(request, 'orders/order/list.html', {'orders' : orders})
    except Exception as e:
        return HttpResponse("Error: {}".format(str(e)), status=500)

def order_detail(request, id):
    try:
        order = get_object_or_404(Order, id=id)
        customer = order.customer
        user = get_object_or_404(User, id=customer.pk)
        order_items = OrderItem.objects.filter(order_id=order.id)
        return render(request, 'orders/order/detail.html', {'order' : order, 'user': user, 'order_items': order_items})
    except Exception as e:
            return HttpResponse("Error: {}".format(str(e)), status=500)

orders/templates/orders/order/create.html
{% extends "base.html" %}

{% block title %}Checkout{% endblock %}

{% block content %}

<div class="container my-5">
    <h1 class="text-center mb-5">Checkout</h1>
    <div class="row">
        <div class="col-md-6 order-info">
            <h3>Your order</h3>
            <ul class="list-group">
                {% for item in cart %}
                <li class="list-group-item">
                    <span class="font-weight-bold">{{ item.quantity }}x {{ item.product.name }}</span>
                    <span class="float-right">${{ item.total_price }}</span>
                </li>
                {% endfor %}
            </ul>
            <p class="font-weight-bold mt-3">Total: ${{ cart.get_total_price }}</p>
        </div>
        <div class="col-md-6 order-form">
            <h3>Fill in the form</h3>
            <form action="." method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <p><input type="submit" value="Place order" class="btn btn-primary"></p>
            </form>
        </div>
    </div>
</div>

{% endblock %}

orders/templates/orders/order/created.html
{% extends "base.html" %}

{% block title %}Thank you{% endblock %}

{% block content %}

<div class="container text-center">
    <h1 class="mb-4">Thank you</h1>
    <p>Your order has been successfully completed. Your order number is
    <strong>{{ order.id }}</strong>.</p>
</div>

{% endblock %}

orders/templates/orders/order/detail.html
{% extends 'base.html' %}

{% block title %}Order Details{% endblock %}

{% block content %}

    <div class="container mt-5">
        <h1>Order Details</h1>

        <div class="text-right">
            <a href="{% url 'orders:order_list' %}" class="btn btn-primary">Back</a>
        </div>
            
        <p>Order: 
            This is order {{ order.id }} for {{ user.first_name }} {{ user.last_name }}. The order was placed on: {{ order.created }} 
        </p>
        
        <p>The order includes these items:</p>
        <ul>
            {% for item in order_items %}
                <li>
                    <p>Quantity: {{ item.quantity }}</p>
                    <p>Item: {{ item.product }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

orders/templates/orders/order/list.html
{% extends 'base.html' %}

{% block title %}Order List{% endblock %}

{% block content %}

    <div class="container mt-5">
        <h1>Order List</h1>
    
        {% for order in orders %}
            <p>This is order <b><a href="{% url 'orders:order_detail' id=order.id %}">{{ order.id }}</a></b> for
            {{ order.customer.user }}. The order was placed on: {{ order.created }} </p>
        {% endfor %}
    </div>

{% endblock %}