account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'account'

urlpatterns = [
    path('login/', 
        auth_views.LoginView.as_view(
        template_name='registration/login.html'), name='login'),
    path('logout/', 
        auth_views.LogoutView.as_view(
        template_name='registration/log_out.html'), name='logout'),
    path('', views.dashboard, name='dashboard'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:id>/', views.customer_detail, name= 'customer_detail'),
]

johnsonshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls', namespace='customer')),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order_list/', views.order_list, name='order_list'),
    path('order/<int:id>/', views.order_detail, name= 'order_detail'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('search/', views.product_search, name='product_search'),
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

store/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
    unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
        models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('store:product_list_by_category', args=[self.slug])
    
class Product(models.Model):
    category = models.ForeignKey(
        Category, 
        related_name='products', 
        on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
    blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
    decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
    def __str__(self):
        return self.name
    
    def get_slug(self):
        return self.slug or str(self.id)
    
    def get_absolute_url(self):
        if self.slug:
            return reverse('store:product_detail', args=[self.id, self.slug])
        else:
            return reverse('store:product_detail', args=[self.id, self.get_slug()])

store/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField()

store/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .models import Category, Product
from cart.forms import CartAddProductForm
from store.forms import SearchForm

# Create your views here.

def product_list(request, category_slug=None):
    try:
        
        category = None
        categories = Category.objects.all()
        products = Product.objects.filter(available=True)

        if category_slug:
            category = get_object_or_404(
                Category, 
                slug=category_slug)
            products = products.filter(category=category)

        return render(request,
            'store/product/list.html',
            {'category': category,
            'categories': categories,
            'products': products})

    except Exception as e:
        return HttpResponse("Error: {}".format(str(e)), status=500)


def product_detail(request, id, slug):
    try:
        product = get_object_or_404(Product, id=id, available=True)

        if slug != product.slug:
            if not slug:
                return HttpResponseRedirect(
                    reverse('product_detail', args=[product.id, product.slug]))
            else:
                return HttpResponseRedirect(
                    reverse('product_detail', args=[product.id, product.get_slug()]))

        cart_product_form = CartAddProductForm()

        return render(request,
            'store/product/detail.html',
            {'product': product,
            'cart_product_form': cart_product_form})
    
    except Exception as e:
        return HttpResponse("Error: {}".format(str(e)), status=500)


def product_search(request):
    try:

        query = request.GET.get('query')
        products = []

        if query:
            query_list = query.split()
            q = Q()
            for word in query_list:
                q |= Q(name__icontains=word) | Q(description__icontains=word)
            products = Product.objects.filter(q)

        form = SearchForm(initial={'search_query': query})

        context = {
            'form': form,
            'products': products,
            'query': query,
        }

        return render(request, 'store/product/search.html', context)
    
    except Exception as e:
        return HttpResponse("Error: {}".format(str(e)), status=500)

store/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}Wale's online store{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    </head>
    </head>
    <body>
        {% include 'navbar.html' %}
        
        <div id="content">
            {% block content %}
            
            {% endblock %}
        </div>

        {% block scripts %}

        {% endblock scripts %}

    </body>
</html>

store/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Johnson's Online Store</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link{% if section == 'dashboard' %} active{% endif %}" href="{% url 'account:dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if section == 'customer' %} active{% endif %}" href="{% url 'customer:customer_list' %}">Customers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if section == 'order' %} active{% endif %}" href="{% url 'orders:order_list' %}">Orders</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link{% if section == 'shop' %} active{% endif %}" href="{% url 'store:product_list' %}">Shop</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if section == 'search' %} active{% endif %}" href="{% url 'store:product_search' %}">Search</a>
            </li>
            <li class="nav-item">
              <a class="nav-link{% if section == 'cart' %} active{% endif %}" href="{% url 'cart:cart_detail' %}">
                <i class="bi bi-cart"></i>
                {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                {{ total_items }} item{{ total_items|pluralize }}
                {% else %}
                Empty
                {% endif %}
                {% endwith %}
              </a>
            </li>
            {% endif %}
            <li class="nav-item">
              {% if request.user.is_authenticated %}
              <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
              {% else %}
              <a class="nav-link{% if section == 'login' %} active{% endif %}" href="{% url 'account:login' %}">Login</a>
              {% endif %}
            </li>
        </ul>
      </div>
    </div>
  </nav>
  